import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const srcDir = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(?:[A-Za-z]:)/, (m) => m.slice(1)));
const sourcePath = path.join(srcDir, 'index.js');
const runtimePath = path.join(srcDir, '.index-local-runtime.mjs');

let source = await fs.readFile(sourcePath, 'utf8');

const oldBlock = `  await sleep(700);\n\n  const doneButton = page.getByRole('button', { name: /Hecho|Done/i }).first();\n  if (await doneButton.count().catch(() => 0) && await doneButton.isVisible().catch(() => false)) {\n    await doneButton.click({ timeout: 8000 });\n    await sleep(1400);\n  } else {\n    const doneText = page.getByText(/^(Hecho|Done)$/i).filter({ visible: true }).first();\n    if (await doneText.count().catch(() => 0)) {\n      await doneText.click({ timeout: 8000 });\n      await sleep(1400);\n    }\n  }`;

const firstRuntimeBlock = `  await sleep(700);\n\n  const doneClicked = await page.evaluate(() => {\n    const visible = (el) => {\n      if (!(el instanceof HTMLElement)) return false;\n      const rect = el.getBoundingClientRect();\n      const style = getComputedStyle(el);\n      return rect.width > 0 && rect.height > 0 && style.display !== 'none' && style.visibility !== 'hidden';\n    };\n    const nodes = Array.from(document.querySelectorAll('button,[role=\\"button\\"],[tabindex],span,div'));\n    const textNode = nodes.find((el) => visible(el) && /^(hecho|done)$/i.test(String(el.textContent || '').trim()));\n    if (!textNode) return false;\n    const clickable = textNode.closest('button,[role=\\"button\\"],[tabindex]') || textNode;\n    if (clickable instanceof HTMLElement) { clickable.click(); return true; }\n    return false;\n  });\n  if (!doneClicked) throw new Error('flow_start_frame_done_not_found');\n  await page.waitForFunction(() => {\n    const nodes = Array.from(document.querySelectorAll('button,[role=\\"button\\"],[tabindex],span,div'));\n    return !nodes.some((el) => {\n      if (!(el instanceof HTMLElement)) return false;\n      const rect = el.getBoundingClientRect();\n      const style = getComputedStyle(el);\n      return rect.width > 0 && rect.height > 0 && style.display !== 'none' && style.visibility !== 'hidden' && /^(hecho|done)$/i.test(String(el.textContent || '').trim());\n    });\n  }, { timeout: 10000 }).catch(() => undefined);\n  await sleep(900);`;

const newBlock = `  await sleep(500);\n\n  await page.waitForFunction(() => {\n    const visible = (el) => {\n      if (!(el instanceof HTMLElement)) return false;\n      const rect = el.getBoundingClientRect();\n      const style = getComputedStyle(el);\n      return rect.width > 0 && rect.height > 0 && style.display !== 'none' && style.visibility !== 'hidden';\n    };\n    return Array.from(document.querySelectorAll('button,[role=\\"button\\"],[tabindex],span,div')).some((el) =>\n      visible(el) && /^(hecho|done)$/i.test(String(el.textContent || '').trim())\n    );\n  }, { timeout: 12000 });\n\n  const doneClicked = await page.evaluate(() => {\n    const visible = (el) => {\n      if (!(el instanceof HTMLElement)) return false;\n      const rect = el.getBoundingClientRect();\n      const style = getComputedStyle(el);\n      return rect.width > 0 && rect.height > 0 && style.display !== 'none' && style.visibility !== 'hidden';\n    };\n    const nodes = Array.from(document.querySelectorAll('button,[role=\\"button\\"],[tabindex],span,div'));\n    const textNode = nodes.find((el) => visible(el) && /^(hecho|done)$/i.test(String(el.textContent || '').trim()));\n    if (!textNode) return false;\n    const clickable = textNode.closest('button,[role=\\"button\\"],[tabindex]') || textNode;\n    if (clickable instanceof HTMLElement) { clickable.click(); return true; }\n    return false;\n  });\n  if (!doneClicked) throw new Error('flow_start_frame_done_not_found');\n\n  await page.waitForFunction(() => {\n    const visible = (el) => {\n      if (!(el instanceof HTMLElement)) return false;\n      const rect = el.getBoundingClientRect();\n      const style = getComputedStyle(el);\n      return rect.width > 0 && rect.height > 0 && style.display !== 'none' && style.visibility !== 'hidden';\n    };\n    return !Array.from(document.querySelectorAll('button,[role=\\"button\\"],[tabindex],span,div')).some((el) =>\n      visible(el) && /^(hecho|done)$/i.test(String(el.textContent || '').trim())\n    );\n  }, { timeout: 12000 });\n  await sleep(900);`;

if (source.includes(firstRuntimeBlock)) source = source.replace(firstRuntimeBlock, newBlock);
else if (source.includes(oldBlock)) source = source.replace(oldBlock, newBlock);
else if (!source.includes("flow_start_frame_done_not_found")) {
  throw new Error('local_runner_patch_target_not_found');
}

await fs.writeFile(runtimePath, source, 'utf8');
await import(pathToFileURL(runtimePath).href + `?v=${Date.now()}`);
