-- Scheduling moved to Vercel Cron in vercel.json.
-- Intentionally no database cron/HTTP side effects here: the application route
-- owns reconciliation and Vercel invokes it on schedule using CRON_SECRET.
